Start Playwright migration

diff --git a/.github/workflows/on-pull-request-opened-and-synchronize.yml b/.github/workflows/on-pull-request-opened-and-synchronize.yml
--- a/.github/workflows/on-pull-request-opened-and-synchronize.yml
+++ b/.github/workflows/on-pull-request-opened-and-synchronize.yml
@@ -25,8 +25,8 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
 
-  fetch-playwright-baseline-screenshots:
-    name: Fetch Playwright Baseline Screenshots
+  fetch-baseline-screenshots:
+    name: Fetch Baseline Screenshots
     runs-on: ubuntu-latest
     steps:
       # TODO: Remove after this is resolved: https://www.cloudflarestatus.com/incidents/t5nrjmpxc1cj
@@ -46,12 +46,12 @@ jobs:
           aws configure set output json
           aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
-      - run: aws s3 sync s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/playwright-baseline-screenshots ./playwright-baseline-screenshots --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
-      - name: Upload Playwright Baseline Screenshots
+      - run: aws s3 sync s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/playwright-baseline-screenshots ./dist/playwright-baseline-screenshots --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
+      - name: Upload Baseline Screenshots
         uses: actions/upload-artifact@v4
         with:
-          path: playwright-baseline-screenshots
-          name: playwright-baseline-screenshots
+          path: ./dist/playwright-baseline-screenshots
+          name: baseline-screenshots
 
   format:
     name: Format
@@ -92,11 +92,24 @@ jobs:
         env:
           NODE_ENV: production
 
-  test:
-    name: Test
+  test-lint-rules:
+    name: Test (Lint Rules)
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    needs:
+      - install-dependencies
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/pnpm
+      - run: pnpm start:production:typescript
+      - run: pnpm exec playwright test --config ./src/playwright/playwright.config.ts --project linting
+        env:
+          PLAYWRIGHT_NO_WEBSERVER: true
+
+  test-unmigrated:
+    name: Test (Unmigrated)
     # https://github.com/CrowdStrike/glide-core/pull/529#discussion_r1886905184
     runs-on: macos-latest
-    # Something has gone wrong if the job takes longer than 10 minutes.
     timeout-minutes: 10
     needs:
       - install-dependencies
@@ -104,14 +117,12 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
       - run: pnpm dlx playwright@1.52.0 install --only-shell --with-deps chromium
-      - run: pnpm test
-        env:
-          NODE_ENV: production
+      - run: pnpm test:production:web-test-runner
       - name: Upload Web Test Runner Coverage Report
         uses: actions/upload-artifact@v4
         if: ${{ failure() }}
         with:
-          name: coverage
+          name: web-test-runner-coverage
           path: dist/web-test-runner-coverage
       - name: Upload Web Test Runner Debugging Screenshots
         uses: actions/upload-artifact@v4
@@ -120,16 +131,15 @@ jobs:
           name: web-test-runner-debugging-screenshots
           path: dist/web-test-runner-debugging-screenshots
 
-  # Its own job instead of putting it in `test-visuals` and renaming that job
-  # because `test-visual` sets `continue-on-error` so that missing and changed
-  # snapshots don't cause it to fail.
-  test-aria:
-    name: Test (ARIA)
+  test-functionality:
+    name: Test (Functionality)
     runs-on: ubuntu-latest
-
     timeout-minutes: 5 # Increase sharding if the job takes longer than this
     needs:
       - install-dependencies
+      - build
+    outputs:
+      failed: ${{ steps.get-test-job-outcome.outputs.failed }}
     strategy:
       matrix:
         shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
@@ -137,9 +147,137 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
-      - run: pnpm dlx playwright@1.52.0 install --only-shell --with-deps chromium
+      - name: Download Storybook
+        uses: actions/download-artifact@v4
+        with:
+          name: storybook
+          path: ./dist/storybook
+      - run: pnpm dlx playwright@1.52.0 install --no-shell --with-deps chromium firefox webkit
       - name: Test
-        run: pnpm exec playwright test --project aria --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
+        id: test
+        run: pnpm exec playwright test --config ./src/playwright/playwright.config.ts --project functionality --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
+        continue-on-error: true
+      - name: Get "Test" Job Outcome
+        id: get-test-job-outcome
+        run: |
+          if [ "${{ steps.test.outcome }}" == "failure" ]; then
+            echo "failed=true" >> $GITHUB_OUTPUT
+          fi
+      - name: Upload Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report-${{ matrix.shardIndex }}
+          path: dist/playwright/coverage-report
+      - name: Upload Test Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report-${{ matrix.shardIndex }}
+          path: ./dist/playwright/test-report
+
+  verify-and-deploy-test-report:
+    name: Verify And Deploy Test Report
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    needs:
+      - test-functionality
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/pnpm
+      - name: Download Test Reports
+        uses: actions/download-artifact@v4
+        with:
+          merge-multiple: true
+          path: ./dist/playwright/test-reports
+          pattern: test-report-*
+      - name: Merge Test Reports
+        run: |
+          PLAYWRIGHT_HTML_ATTACHMENTS_BASE_URL=https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref  }}/test-report/data/ pnpm exec playwright merge-reports --config ./src/playwright/playwright.config.ts --reporter html ./dist/playwright/test-reports
+      - name: Install AWS CLI
+        run: |
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          echo "8119ccf67de875f39d386abea986738fa710be57e20d4df66fa99c7f7fd09997 awscliv2.zip" | sha256sum --check
+          unzip awscliv2.zip
+          sudo ./aws/install --update
+      - name: Configure AWS CLI
+        env:
+          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
+          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
+        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
+        run: |
+          aws configure set region auto
+          aws configure set output json
+          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
+      - name: Deploy Test Report
+        run: aws s3 sync ./playwright-report s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }}/test-report --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
+      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728
+        with:
+          header: test-report
+          message: |+
+            ## ${{ needs.test-functionality.outputs.failed && '⚠️' || '✅' }} Test Report
+            https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/test-report#?q=s:${{ needs.test-functionality.outputs.failed && 'failed+s:flaky' || 'passed' }}
+      - name: Report Test Failure
+        if: ${{ needs.test-functionality.outputs.failed == 'true' }}
+        run: |
+          echo One or more tests failed. See the report:
+          echo
+          echo https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/test-report#?q=s:${{ needs.test-functionality.outputs.failed && 'failed+s:flaky' || 'passed' }}
+          exit 1
+
+  verify-and-deploy-coverage-report:
+    name: Verify And Deploy Coverage Report
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    needs:
+      - test-functionality
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/pnpm
+      - name: Download Coverage Reports
+        uses: actions/download-artifact@v4
+        with:
+          path: ./dist/playwright
+          pattern: coverage-report-*
+        # TODO: CI should fail if verification fails. may have to move deploy report to its own step.
+      - name: Merge Coverage Reports
+        id: merge
+        run: pnpm exec tsx ./src/playwright/merge-coverage-reports.ts ${{ github.head_ref }}
+        continue-on-error: true
+      - name: Install AWS CLI
+        run: |
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          echo "8119ccf67de875f39d386abea986738fa710be57e20d4df66fa99c7f7fd09997 awscliv2.zip" | sha256sum --check
+          unzip awscliv2.zip
+          sudo ./aws/install --update
+      - name: Configure AWS CLI
+        env:
+          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
+          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
+        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
+        run: |
+          aws configure set region auto
+          aws configure set output json
+          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
+      - name: Deploy Coverage Report
+        run: aws s3 sync ./dist/playwright/coverage-report s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }}/coverage-report --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
+      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728
+        with:
+          header: coverage-report
+          message: |+
+            ## ${{ steps.merge.outcome == 'failure' && '⚠️' || '✅' }} Coverage Report
+            https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/coverage-report
+      - name: Report Insufficient Coverage
+        if: ${{ steps.merge.outcome == 'failure' }}
+        run: |
+          echo Insufficient test coverage. See the report:
+          echo
+          echo https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/coverage-report
+          exit 1
 
   test-visuals:
     name: Test (Visuals)
@@ -147,7 +285,7 @@ jobs:
     timeout-minutes: 5 # Increase sharding if the job takes longer this
     needs:
       - install-dependencies
-      - fetch-playwright-baseline-screenshots
+      - fetch-baseline-screenshots
     outputs:
       failed: ${{ steps.get-test-job-outcome.outputs.failed }}
     strategy:
@@ -159,62 +297,48 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
-      - run: pnpm dlx playwright@1.52.0 install --only-shell --with-deps chromium
-      - name: Download Playwright Baseline Screenshots
+      - run: pnpm dlx playwright@1.52.0 install --no-shell --with-deps chromium
+      - name: Download Baseline Screenshots
         uses: actions/download-artifact@v4
         with:
+          name: baseline-screenshots
           path: dist/playwright-baseline-screenshots
-          name: playwright-baseline-screenshots
       - name: Test
         id: test
-        # Failing would add quite a bit of time to CI. It would also add complexity, both
-        # for developers and to this workflow.
-        #
-        # To do it, we'd have to hack up GitHub's staged deployments feature to require
-        # an approval of the visual changes. After they're approved, we'd update the
-        # screenshots on R2. Then we'd force a re-run of this job so it passes for the
-        # branch in question. Lastly, after merge, we'd have to synchronize the
-        # screenshots again in case another branch was merged in the meantime and
-        # overwrote them.
-        #
-        # So we simply expect the developer and reviewers to look over the test report,
-        # deployed below, before merging.
         continue-on-error: true
-        run: pnpm exec playwright test --project visuals --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
-      - name: Get `test` job outcome
+        run: pnpm exec playwright test --config ./src/playwright/playwright.config.ts --project visuals --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
+      - name: Get "Test" Job Outcome
         id: get-test-job-outcome
         run: |
           if [ "${{ steps.test.outcome }}" == "failure" ]; then
             echo "failed=true" >> $GITHUB_OUTPUT
           fi
-      - name: Upload blob report
-        if: ${{ !cancelled() }}
+      - name: Upload Report
         uses: actions/upload-artifact@v4
         with:
-          name: visual-test-report-blob-${{ matrix.shardIndex }}
-          path: blob-report
+          name: visual-report-${{ matrix.shardIndex }}
+          path: ./dist/playwright/test-report
 
-  deploy-visual-test-report:
-    name: Deploy Visual Test Report
+  deploy-visual-report:
+    name: Deploy Visual Report
     runs-on: ubuntu-latest
     permissions:
       contents: read
       pull-requests: write
-    if: ${{ !cancelled() }}
     needs:
       - test-visuals
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
-      - name: Download Blob Reports
+      - name: Download Reports
         uses: actions/download-artifact@v4
         with:
           merge-multiple: true
-          path: visual-test-report-blob
-          pattern: visual-test-report-blob-*
-      - name: Merge Blob Reports
+          path: ./dist/playwright/test-reports
+          pattern: visual-report-*
+      - name: Merge Reports
         run: |
-          PLAYWRIGHT_HTML_ATTACHMENTS_BASE_URL=https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref  }}/visual-test-report/data/ pnpm exec playwright merge-reports --reporter html ./visual-test-report-blob
+          PLAYWRIGHT_HTML_ATTACHMENTS_BASE_URL=https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref  }}/visual-report/data/ pnpm exec playwright merge-reports --config ./src/playwright/playwright.config.ts --reporter html ./dist/playwright/test-reports
       # TODO: Remove after this is resolved: https://www.cloudflarestatus.com/incidents/t5nrjmpxc1cj
       - name: Install AWS CLI
         run: |
@@ -232,14 +356,14 @@ jobs:
           aws configure set output json
           aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
-      - name: Deploy HTML Report
-        run: aws s3 sync ./playwright-report s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }}/visual-test-report --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
+      - name: Deploy Report
+        run: aws s3 sync ./playwright-report s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }}/visual-report --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
       - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728
         with:
-          header: visual-test-report
+          header: visual-report
           message: |+
-            ## ${{ needs.test-visuals.outputs.failed && '⚠️' || '✅' }} Visual Test Report
-            https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/visual-test-report
+            ## ${{ needs.test-visuals.outputs.failed && '⚠️' || '✅' }} Visual Report
+            https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/visual-report#?q=s:${{ needs.test-visuals.outputs.failed && 'failed+s:flaky' || 'passed' }}
 
   build:
     name: Build
