Finish configuring Playwright

diff --git a/.github/workflows/on-pull-request-opened-and-synchronize.yml b/.github/workflows/on-pull-request-opened-and-synchronize.yml
--- a/.github/workflows/on-pull-request-opened-and-synchronize.yml
+++ b/.github/workflows/on-pull-request-opened-and-synchronize.yml
@@ -106,7 +106,7 @@ jobs:
         env:
           PLAYWRIGHT_NO_WEBSERVER: true
   test:
-    name: Test
+    name: Test (Unmigrated)
     # https://github.com/CrowdStrike/glide-core/pull/529#discussion_r1886905184
     runs-on: macos-latest
     # Something has gone wrong if the job takes longer than 10 minutes.
@@ -117,21 +117,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
       - run: pnpm dlx playwright@1.54.2 install --only-shell --with-deps chromium
-      - run: pnpm test
-        env:
-          NODE_ENV: production
-      - name: Upload Web Test Runner Coverage Report
-        uses: actions/upload-artifact@v4
-        if: ${{ failure() }}
-        with:
-          name: coverage
-          path: dist/web-test-runner-coverage
-      - name: Upload Web Test Runner Debugging Screenshots
-        uses: actions/upload-artifact@v4
-        if: ${{ always() }}
-        with:
-          name: web-test-runner-debugging-screenshots
-          path: dist/web-test-runner-debugging-screenshots
+      - run: pnpm test:production:web-test-runner
 
   test-functionality:
     name: Test (Functionality)
@@ -140,6 +126,9 @@ jobs:
     timeout-minutes: 5 # Increase sharding if the job takes longer than this
     needs:
       - install-dependencies
+      - build
+    outputs:
+      failed: ${{ steps.get-test-job-outcome.outputs.failed }}
     strategy:
       matrix:
         shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
@@ -147,9 +136,136 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/pnpm
-      - run: pnpm dlx playwright@1.54.2 install --no-shell --with-deps chromium
+      - name: Download Storybook
+        uses: actions/download-artifact@v4
+        with:
+          name: storybook
+          path: ./dist/storybook
+      - run: pnpm dlx playwright@1.54.2 install --no-shell --with-deps chromium firefox webkit
       - name: Test
+        id: test
         run: pnpm exec playwright test --config ./src/playwright/playwright.config.ts --project functionality --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
+        continue-on-error: true
+      - name: Get "Test" Job Outcome
+        id: get-test-job-outcome
+        run: |
+          if [ "${{ steps.test.outcome }}" == "failure" ]; then
+            echo "failed=true" >> $GITHUB_OUTPUT
+          fi
+      - name: Upload Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report-${{ matrix.shardIndex }}
+          path: dist/playwright/coverage-report
+      - name: Upload Test Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report-${{ matrix.shardIndex }}
+          path: ./dist/playwright/test-report
+
+  verify-and-deploy-test-report:
+    name: Verify And Deploy Test Report
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    needs:
+      - test-functionality
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/pnpm
+      - name: Download Test Reports
+        uses: actions/download-artifact@v4
+        with:
+          merge-multiple: true
+          path: ./dist/playwright/test-reports
+          pattern: test-report-*
+      - name: Merge Test Reports
+        run: |
+          PLAYWRIGHT_HTML_ATTACHMENTS_BASE_URL=https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref  }}/test-report/data/ pnpm exec playwright merge-reports --config ./src/playwright/playwright.config.ts --reporter html ./dist/playwright/test-reports
+      - name: Install AWS CLI
+        run: |
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          echo "8119ccf67de875f39d386abea986738fa710be57e20d4df66fa99c7f7fd09997 awscliv2.zip" | sha256sum --check
+          unzip awscliv2.zip
+          sudo ./aws/install --update
+      - name: Configure AWS CLI
+        env:
+          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
+          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
+        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
+        run: |
+          aws configure set region auto
+          aws configure set output json
+          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
+      - name: Deploy Test Report
+        run: aws s3 sync ./playwright-report s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }}/test-report --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
+      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728
+        with:
+          header: test-report
+          message: |+
+            ## ${{ needs.test-functionality.outputs.failed && '⚠️' || '✅' }} Test Report
+            https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/test-report#?q=s:${{ needs.test-functionality.outputs.failed && 'failed+s:flaky' || 'passed' }}
+      - name: Report Test Failure
+        if: ${{ needs.test-functionality.outputs.failed == 'true' }}
+        run: |
+          echo One or more tests failed. See the report:
+          echo
+          echo https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/test-report#?q=s:${{ needs.test-functionality.outputs.failed && 'failed+s:flaky' || 'passed' }}
+          exit 1
+
+  verify-and-deploy-coverage-report:
+    name: Verify And Deploy Coverage Report
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    needs:
+      - test-functionality
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/pnpm
+      - name: Download Coverage Reports
+        uses: actions/download-artifact@v4
+        with:
+          path: ./dist/playwright
+          pattern: coverage-report-*
+      - name: Merge Coverage Reports
+        id: merge
+        run: pnpm exec tsx ./src/playwright/merge-coverage-reports.ts ${{ github.head_ref }}
+        continue-on-error: true
+      - name: Install AWS CLI
+        run: |
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          echo "8119ccf67de875f39d386abea986738fa710be57e20d4df66fa99c7f7fd09997 awscliv2.zip" | sha256sum --check
+          unzip awscliv2.zip
+          sudo ./aws/install --update
+      - name: Configure AWS CLI
+        env:
+          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
+          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
+        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
+        run: |
+          aws configure set region auto
+          aws configure set output json
+          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
+      - name: Deploy Coverage Report
+        run: aws s3 sync ./dist/playwright/coverage-report s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }}/coverage-report --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
+      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728
+        with:
+          header: coverage-report
+          message: |+
+            ## ${{ steps.merge.outcome == 'failure' && '⚠️' || '✅' }} Coverage Report
+            https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/coverage-report
+      - name: Report Insufficient Coverage
+        if: ${{ steps.merge.outcome == 'failure' }}
+        run: |
+          echo Insufficient test coverage. See the report:
+          echo
+          echo https://${{ vars.CLOUDFLARE_CUSTOM_DOMAIN }}/${{ github.head_ref }}/coverage-report
+          exit 1
 
   test-visuals:
     name: Test (Visuals)
