Harden workflows (#796)

diff --git a/.github/workflows/on-pull-request-closed.yml b/.github/workflows/on-pull-request-closed.yml
--- a/.github/workflows/on-pull-request-closed.yml
+++ b/.github/workflows/on-pull-request-closed.yml
@@ -4,6 +4,12 @@ on:
   pull_request:
     types: [closed]
 
+permissions: {}
+
+defaults:
+  run:
+    shell: bash -eu -o pipefail {0}
+
 jobs:
   remove-cloudflare-artifacts:
     name: Remove Cloudflare artifacts
@@ -15,6 +21,7 @@ jobs:
       - name: Install AWS CLI
         run: |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          echo "8119ccf67de875f39d386abea986738fa710be57e20d4df66fa99c7f7fd09997 awscliv2.zip" | sha256sum --check
           unzip awscliv2.zip
           sudo ./aws/install --update
       - name: Configure AWS CLI
@@ -28,4 +35,12 @@ jobs:
           aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
       - name: Remove artifacts
-        run: aws s3 rm s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }} --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }} --recursive
+        run: |
+          BRANCH="${{ github.head_ref }}"
+
+          if [[ ! $BRANCH =~ ^[a-zA-Z0-9_\-\/]+$ ]]; then
+            echo "Invalid branch name"
+            exit 1
+          fi
+
+          aws s3 rm s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }} --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }} --recursive
